### ISSUE TITLE
PHP 8.0 required parameter ordering deprecation warnings

### ISSUE THREAD

**Issue by thepurpleblob** [moodleou/moodle-mod_oublog#126]
Quite a few "Required parameter XXX follows optional parameter YYY" in this plugin. Lines as follows...

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L638-L639

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L1147

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L3404-L3406

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L3591-L3594

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L4507-L4508

https://github.com/moodleou/moodle-mod_oublog/blob/bd3d62ba0eb55e006064af5ec881f92afcb51c4d/locallib.php#L4623-L4624

**Comment by sammarshallou** [comment]
We just went live with PHP8 yesterday, but we hadn't pushed github branches for a bit... I have done so now, this should be updated on MOODLE_311_STABLE and master branches. Hopefully that fixes it so I'm going to go ahead and close this issue, please reopen if needed.
