### ISSUE TITLE
Moodle 4.0 support?

### ISSUE THREAD

**Issue by paaskynen** [moodleou/moodle-mod_oublog#130]
Thanks for this useful plugin. As the Moodle 3 branch is nearing its terminus, is there a Moodle 4 version of this plugin in the works?

**Comment by sammarshallou** [comment]
Our plugins have been updated to work on Moodle 4 (we are live with 4.0.something since December), but we had neglected to run the script to update GitHub, apologies. I've run it now, so the MOODLE_400_STABLE branch should now exist (along with a final update to MOODLE_311_STABLE).
