### ISSUE TITLE
In M4.4, Passing a courseid to format_text() is deprecated, please pass a context instead

### ISSUE THREAD

**Issue by lbailey-ucsf** [moodleou/moodle-mod_oublog#148]
Line 2698 in locallib.php should be changed to something like `format_text($comment->message, FORMAT_MOODLE, ['context' => $oublog->course,])`

Testing the 403 branch against M4.4 outputs the following error. I assume this was addressed in a soon to be released 404 branch that was slated for end of October/Early November 2024. If it has already been fixed, any thoughts on when the 404 branch will be released?

```
1) oublog_locallib_test::test_oublog_add_comment
Unexpected debugging() call detected.
Debugging: Passing a courseid to format_text() is deprecated, please pass a context instead.
* line 1383 of /lib/weblib.php: call to debugging()
* line 2698 of /mod/oublog/locallib.php: call to format_text()
* line 169 of /mod/oublog/tests/locallib_test.php: call to oublog_add_comment_moderated()
* line 1617 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to oublog_locallib_test->test_oublog_add_comment()
* line 1223 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 72 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 729 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 973 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 685 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 685 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 685 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 651 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 146 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->run()
* line 99 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 107 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
* line 122 of /vendor/bin/phpunit: call to include()
```

**Comment by stopfstedt** [comment]
@lbailey-ucsf this appears to have been fixed in commit https://github.com/moodleou/moodle-mod_oublog/commit/0941359ff64b2e0a6903bf268dab26fd50486874, but hasn't shipped yet.

i'm seconding the question about a 4.4 release. 

is there anything that i can contribute to push on this to completion line?

**Comment by jason-platts** [comment]
Thanks for reporting this. As mentioned it's hopefully fixed in the 403 branch.

This is a good reminder to push our latest code to 404 - will hopefully get that done this week.

**Comment by sammarshallou** [comment]
Apologies, I forgot to change a setting which means our 4.3 branch is very out of date (just as we are about to abandon it). 

(Jason - it was based on OUVLE_462 still, oops. I've been running updates regularly so you'd think I would have noticed but...)

I have now updated the 403 branch and also (slightly early because we didn't release it yet) the 404 branch.

**Comment by jason-platts** [comment]
Thanks Sam. I've also been able to update moodle plugins DB this time so everything is up to date now.
