### ISSUE TITLE
Moodle 2.5 Blog posts cant have more than 13 attachments 

### ISSUE THREAD

**Issue by mchaney2010** [moodleou/moodle-mod_oublog#41]
Add the ou blog as a mod to a course. 
The user (teacher) selects that they wish to allow the users to attach 100 attachments in the drop down. 
The teacher saves this 
The student goes in and adds a blog post, attempts to upload more than 13 files and it complains. There is also an additional message above the file upload to tell them that they can only upload 13 files. 
If you change the original select to 50 files instead of 100, it only lets them add 12 files. This behavior got me exploring. The values of the options in the select are numerical, 1 - 13. The text in the options are 1 - 10, 20, 50 and 100. 
The form (mod_form.php, line 87 adds the options as an array and it simply takes the value of the option and puts that in the database):

// Max number of attachments.
            $choices = array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50, 100);
            $mform->addElement('select', 'maxattachments',
                    get_string('maxattachments', 'oublog'), $choices);

So 100 is the 14th element in the array, the value will be 13. When it does the insert on line 40 of lib.php then it doesnt check what the value -> option corresponds to.

Well, thats my thinking, apologies if I just barked up the wrong tree.

**Comment by mchaney2010** [comment]
Hi, I downloaded the latest version of the plugin from Moodle.org (for 2.7) and the issue looks as if it still remains: 

![image](https://cloud.githubusercontent.com/assets/8657036/6058533/10f6fec8-ad20-11e4-95d1-0be744ae30fd.png)

It states that the maximum number of up loadable files is 13. When you try and upload 14 it fails. 

Thanks

Mark

**Comment by jason-platts** [comment]
This issue is still open. I hope to try and fix in the next few weeks.

**Comment by jason-platts** [comment]
Fixed in master, thanks for reporting.
