### ISSUE TITLE
Separate individual blogs- gives error

### ISSUE THREAD

**Issue by iritherman** [moodleou/moodle-mod_oublog#42]
Hi
I installed moodle-mod_oublog-master.zip on moodle 2.7
when i"m changing to Separate individual blogs it give an error -Error reading from database.

Irith

**Comment by jason-platts** [comment]
https://github.com/moodleou/moodle-mod_oublog/commit/1d5a7ca99b027fd400c4e33ddb6c5ad2541e2fe9
