### ISSUE TITLE
textlib calls emit Debugging noise in Moodle 2.8 (now renamed core_text)

### ISSUE THREAD

**Issue by doctorlard** [moodleou/moodle-mod_oublog#47]
Calls such as

    $tagname = textlib::strtolower($bcoursename);

generate debugging noise in Moodle 2.8, which fails PHPUnit testing with:

    Debugging: Class 'textlib' has been renamed for the autoloader and is now deprecated.
    Please use 'core_text' instead.

This should be simple to fix :-)

**Comment by jason-platts** [comment]
Fixed in master, thanks for reporting.
