### ISSUE TITLE
duplicate field in get posts query

### ISSUE THREAD

**Issue by rbonatuvic** [moodleou/moodle-mod_oublog#51]
As of 2015-04-29 in file locallib.php in method oublog_get_posts on line 592, query string starts:
    ``` $fieldlist = "p.*, p.timeposted, p.timeposted AS timecreated,  bi.oublogid, $usernamefields```
The inclusion of p.timeposted is redundant with ```p.*```
This will cause an error in Oracle: ORA-00918: column ambiguously defined.

**Comment by jason-platts** [comment]
Thanks for the bug report. I have fixed this in master branch and will be upstream in our next push.
