### ISSUE TITLE
3.0 PHPUnit test failure

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-mod_oublog#54]
Moodle 3.0 stable / OUblog master branch / MySQL 5.5.46
Aware of the release schedule, noting this for reference. I don't think it breaks anything from the looks of it but not sure what is causing this nor can I see an obvious/easy fix.

Debugging: External function parameters: invalid OPTIONAL value specified.
* line 570 of /lib/externallib.php: call to debugging()
* line 121 of /mod/oublog/externallib.php: call to external_function_parameters->__construct()
* line ? of unknownfile: call to mod_oublog_external::get_blog_allposts_parameters()
* line 82 of /lib/externallib.php: call to call_user_func()
* line 286 of /lib/tests/externallib_test.php: call to external_function_info()
* line ? of unknownfile: call to core_externallib_testcase->test_all_external_info()
* line 886 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 746 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 601 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 702 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 432 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 100 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 47 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()
E.Debugging: External function parameters: invalid OPTIONAL value specified.
* line 570 of /lib/externallib.php: call to debugging()
* line 190 of /mod/oublog/externallib.php: call to external_function_parameters->__construct()
* line ? of unknownfile: call to mod_oublog_external::get_blog_posts_parameters()
* line 82 of /lib/externallib.php: call to call_user_func()
* line 286 of /lib/tests/externallib_test.php: call to external_function_info()
* line ? of unknownfile: call to core_externallib_testcase->test_all_external_info()
* line 886 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 746 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 601 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 702 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 735 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 432 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 100 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 47 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit_TextUI_Command::main()

**Comment by moodlebeuth** [comment]
Hello,

I can confirm this test failure also for moodle (version 2.8.9+ / Build: 20151119), oublog (branch 2.8 r2/version 2015072200) and Postgresql (version 9.4.4):
Debugging: External function parameters: invalid OPTIONAL value specified.
* line 545 of /lib/externallib.php: call to debugging()
* line 121 of /mod/oublog/externallib.php: call to external_function_parameters->__construct()
* line ? of unknownfile: call to mod_oublog_external::get_blog_allposts_parameters()
* line 74 of /lib/externallib.php: call to call_user_func()
* line 235 of /lib/tests/externallib_test.php: call to external_function_info()
* line ? of unknownfile: call to core_externallib_testcase->test_all_external_info()
* line 988 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 838 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 648 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 783 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 779 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 749 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->runTest()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 350 of /vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 176 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 129 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 63 of /vendor/phpunit/phpunit/composer/bin/phpunit: call to PHPUnit_TextUI_Command::main()
<b>My NOTICE</b> [1024] Unexpected debugging() call detected.<br />
..Debugging: External function parameters: invalid OPTIONAL value specified.
* line 545 of /lib/externallib.php: call to debugging()
* line 190 of /mod/oublog/externallib.php: call to external_function_parameters->__construct()
* line ? of unknownfile: call to mod_oublog_external::get_blog_posts_parameters()
* line 74 of /lib/externallib.php: call to call_user_func()
* line 235 of /lib/tests/externallib_test.php: call to external_function_info()
* line ? of unknownfile: call to core_externallib_testcase->test_all_external_info()
* line 988 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 838 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 648 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 783 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 779 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 749 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->runTest()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 709 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->run()
* line 350 of /vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 176 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 129 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 63 of /vendor/phpunit/phpunit/composer/bin/phpunit: call to PHPUnit_TextUI_Command::main()
<b>My NOTICE</b> [1024] Unexpected debugging() call detected.<br />

Thanks & Greetings,
Michael

**Comment by eugeneventer** [comment]
The above patch seems to fix this issue ;)

**Comment by jason-platts** [comment]
Thanks! Sorry, hadn't spotted this breaks unit tests as hadn't realised there was a core test that tests all the external lib files. I'll use your patch as it looks correct - it may take some time to get upstream to github though... so if anyone encounters this issue use the patch above.

**Comment by aspark21** [comment]
Patch is now upstreamed in master branch
