### ISSUE TITLE
OU Blogs creates grade entry

### ISSUE THREAD

**Issue by rlorenzo** [moodleou/moodle-mod_oublog#56]
OU Blog creates a grade entry in grade book, even when requested not to.

1. Create OU Blog assignment (ex. at https://ccle.ucla.edu/course/view/kudymatest?section=6)
2. In Settings:
  - set grading to "No grade (Default)"
  - set Ratings > Aggregate Type to "No Ratings"
3. Check grade book grader report, there is a category for OU Blog listed.
4. When in the OU Blog Assignment page, click "Participation by User" and it has dropdown for assigning grades to users

We are using OU Blog version 2015011200.

If a Blog is set to have no grade, we are expecting that the activity doesn't show up in the gradebook and that the grading options are turned off.

**Comment by jason-platts** [comment]
Thanks for reporting this. I see the same thing myself so will investigate.

**Comment by jason-platts** [comment]
I've now fixed this and it should be upstream next time we push.

Have attached a zip of the patch for this for use until then.
[blogfix56.zip](https://github.com/moodleou/moodle-mod_oublog/files/112251/blogfix56.zip)
