### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by ajo-sc** [moodleou/moodle-mod_oublog#63]
Hi, we've had your plugin running happily on Moodle 2.5 and it's been really great, but I've just tested out the 3.0 version and it's pulling up an SQL error when trying to load the blog posts (see below).

Any assistance you could provide would be very much appreciated!

Thank you,

Mandy

Debug info: SQLState: 42000<br>
Error Code: 1033<br>
Message: [Microsoft][SQL Server Native Client 11.0][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP or FOR XML is also specified.<br>

SELECT COUNT(1) FROM (SELECT id, title, message, timeposted
FROM mdl_oublog_posts
WHERE oubloginstancesid = (
SELECT id
FROM mdl_oublog_instances
WHERE oublogid = '2' AND userid = '13'
)
AND timedeleted IS NULL 
ORDER BY timeposted DESC) as p
[array (
0 => '2',
1 => '13',
)] 

Error code: dmlreadexception
Stack trace:
line 443 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 850 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 898 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 1480 of \lib\dml\moodle_database.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 1553 of \lib\dml\moodle_database.php: call to moodle_database->get_record_sql()
line 3262 of \mod\oublog\locallib.php: call to moodle_database->get_field_sql()
line 4076 of \mod\oublog\locallib.php: call to oublog_get_user_participation()
line 322 of \mod\oublog\view.php: call to oublog_stats_output_myparticipation()

**Comment by jason-platts** [comment]
We are re-using the SQL in the sub-query, and in this case the ORDER BY is not needed.
So it should be possible to fix this, though this approach is used in a number of places.

**Comment by ajo-sc** [comment]
Oh okay. Does that mean you'll be able to fix it in a new version or is it something we'd need to look at ourselves? Thank you.

**Comment by jason-platts** [comment]
We will fix it, it will be pushed to the MASTER branch in github.

If you need to fix this immediately and have access to the php files you can comment out lines 322-331 of view.php to remove the usage 'block' where this error is happening.

**Comment by ajo-sc** [comment]
That's great, thank you very much for your help!
