### ISSUE TITLE
3.1 Tag API - Unit Test Failure

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-mod_oublog#64]
Moodle: 3.1 Stable branch
OUBlog: Letest master branch
DB: MySQL 5.5.41
Aware of the [release schedule](http://learn1.open.ac.uk/mod/oublog/viewpost.php?post=0&u=sm449&time=1369232093), logging for reference.

https://travis-ci.org/aspark21/moodle/jobs/138745275#L1771

4) oublog_locallib_test::test_oublog_tags
mysqli::real_escape_string() expects parameter 1 to be string, array given
/home/travis/build/aspark21/moodle/lib/dml/mysqli_native_moodle_database.php:955
/home/travis/build/aspark21/moodle/lib/dml/mysqli_native_moodle_database.php:1167
/home/travis/build/aspark21/moodle/lib/dml/mysqli_native_moodle_database.php:1218
/home/travis/build/aspark21/moodle/mod/oublog/lib.php:50
/home/travis/build/aspark21/moodle/course/modlib.php:121
/home/travis/build/aspark21/moodle/lib/testing/generator/module_generator.php:266
/home/travis/build/aspark21/moodle/mod/oublog/tests/generator/lib.php:80
/home/travis/build/aspark21/moodle/mod/oublog/tests/oublog_test_lib.php:87
/home/travis/build/aspark21/moodle/mod/oublog/tests/locallib_test.php:1455
/home/travis/build/aspark21/moodle/lib/phpunit/classes/advanced_testcase.php:80

**Comment by jason-platts** [comment]
Fixed on master...
