### ISSUE TITLE
Error saving settings when enabling tags

### ISSUE THREAD

**Issue by mnieuwhof** [moodleou/moodle-mod_oublog#69]
Hi,
When I fill in some tags seperated by a comma in the Tags settings field, and I choose the option to allow predefined tags only I get an error when applying the plugin settings (sorry in  Dutch):

> _Fout in de programmeercode gevonden. Dit moet door een programmeur hersteld worden. moodle_database::get_in_or_equal() does not accept empty arrays_

When I remove all the tags from the tags input box I can save the plugin settings.

Moodle version: v3.1.2

Thank you,
Marc Nieuwhof

**Comment by jason-platts** [comment]
Fixed on master...

**Comment by mnieuwhof** [comment]
Thank you...

2016-11-17 13:22 GMT+01:00 Jason Platts <notifications@github.com>:
