### ISSUE TITLE
Undefined $count variable (lib.php)

### ISSUE THREAD

**Issue by nadavkav** [moodleou/moodle-mod_oublog#72]
https://github.com/moodleou/moodle-mod_oublog/blob/master/lib.php#L567

Please have a look at this.
(Maybe redundant || maybe important?)

**Comment by nadavkav** [comment]
Maybe should be...
$count=count($coursemodules)

**Comment by jason-platts** [comment]
I think it should be $instances==count($coursemodules)

**Comment by nadavkav** [comment]
I will try (thanks)

**Comment by jason-platts** [comment]
Think I fixed this... so change will be on master when we next push upstream.

**Comment by sammarshallou** [comment]
Updated on master now

**Comment by nadavkav** [comment]
Bless you and :tada: merry christmas :tada:
