### ISSUE TITLE
Does not support Privacy API

### ISSUE THREAD

**Issue by thepurpleblob** [moodleou/moodle-mod_oublog#83]
Could support be added for the new privacy API please?

**Comment by sammarshallou** [comment]
Yes we're going to add support for this, in oublog and our other 200 plugins... Not coded yet but it should happen in our master branch within about the next month I hope. (Yes, I know we are late with our GDPR implementation.)

**Comment by kristian-94** [comment]
Hey guys, did anything happen with getting the plugin GDPR compliant?

**Comment by jason-platts** [comment]
Sorry, forgot to close this issue. Privacy API support was added to the 3.5 branch.

**Comment by kristian-94** [comment]
Awesome, thanks
