### ISSUE TITLE
ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by rbonatuvic** [moodleou/moodle-mod_oublog#85]
#84

An example from oublog_import_getallposts in locallib.php:

dml_read_exception: Error reading from database (ORA-00933: SQL command not properly ended
SELECT count(tot.id) FROM (SELECT p.id, p.timeposted, p.title
        FROM t_oublog_posts p
        INNER JOIN t_oublog_instances bi on bi.id = p.oubloginstancesid
        
        WHERE bi.userid = :o_param1
        AND bi.oublogid = :o_param2
        AND p.deletedby IS NULL
        
        ORDER BY p.timeposted DESC) as tot
[array (
  'o_param1' => '3',
  'o_param2' => 2,
)])

The presence of 'as' keyword for aliasing a table or select is unnecessary and should be removed. The above is an example there are 11 instances of this in locallib.php.

**Comment by jason-platts** [comment]
Thanks for the fix - will turn up in Master branch on our next update.
