### ISSUE TITLE
license type "Copyright 2012 The Open University"

### ISSUE THREAD

**Issue by nemelaverde** [moodleou/moodle-mod_oublog#86]
Hello,

I would like to know about the license type managed by the Ou Blog activity.
In the file README appear the text "Copyright 2012 The Open University".I have the doubt if the license was only this year or remained
nowadays.
I need to modify the css, spanish language file and add new logic but i would like to ask for autorization to do it or some contact to communicate with you.

Thanks.

**Comment by sammarshallou** [comment]
OU blog, same as Moodle, is in the GPL license. 

You are welcome to contribute modifications.

The copyright dates usually are the earliest date a file was created, i.e. we don't normally update those dates or authors when modifying a file.

**Comment by nemelaverde** [comment]
Thanks sammarshallou.
