### ISSUE TITLE
Report card error

### ISSUE THREAD

**Issue by Asuskf** [moodleou/moodle-mod_oublog#94]
Blog ratings are not reflected in the report card
Plugin: version 3.5 r1
Moodle 3.6

**Comment by marchelo2212** [comment]
I see the same in my moodle, please help with this.... 

Best regards!

**Comment by marchelo2212** [comment]
I reviewed all the documentation and the moodle forum about OA blog, and I found a solution:
In the OA blog configuration on Ratings area use de "Ratings" option before I use other option (teacher grades to students) but did't work fine.
With "Rating" option the grades see on the report card.

Please close this isue...

Best Regards!
Marcelo
